## PyTorch in One Hour: From Tensors to Training Neural Networks on Multiple GPUs

In [1]:
import torch

# Create a 0D tensor
tensor0D = torch.tensor(1)

# Create a 1D tensor
tensor1D = torch.tensor([1, 2, 3])

# Create a 2D tensor
tensor2D = torch.tensor([[1, 2], [3, 4]])

# Create a 3D tensor
tensor3D = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

#### NOTE: PyTorch adopts the default 64-bit integer data type from Python

In [2]:
print(tensor1D.dtype)

torch.int64


#### If we create tensors from Python floats, PyTorch creates tensors with a 32-bit precision by default, as we can see below:

In [8]:
floatvec = torch.tensor([2.0, 3.0, 4.0])
print(floatvec)
print(floatvec.dtype)

tensor([2., 3., 4.])
torch.float32


#### changing a 64-bit integer tensor into a 32-bit float tensor

In [9]:
floatvec = tensor1D.to(torch.float32)
print(floatvec)
print(floatvec.dtype)

tensor([1., 2., 3.])
torch.float32


In [13]:
tensor2D = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2D

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
# shape of the tensor
print(tensor2D.shape)

torch.Size([2, 3])


#### For reshaping the tensor dimensions

##### Method 01: use `.reshape()`

In [20]:
tensor2D.reshape(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

##### Method 02: use `.view()`

In [21]:
tensor2D.view(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

#### Transpose a tensor

In [22]:
tensor2D.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

#### To multiply two matrices in Pytorch

##### Method 01: `.matmul` method:

In [23]:
tensor2D.matmul(tensor2D.T)

tensor([[14, 32],
        [32, 77]])

##### Method 02: use `@` operator:

In [24]:
tensor2D @ tensor2D.T

tensor([[14, 32],
        [32, 77]])