In [1]:
import torch

In [2]:
import torch.nn.functional as F

#### Single layer perceptron

In [4]:
y = torch.tensor([1.0]) # output
x1 = torch.tensor([1.1]) # intput
w1 = torch.tensor([2.2]) # weight
b = torch.tensor([0.0]) # bias

z = x1 * w1 + b # net input
a = torch.sigmoid(z) # activation & output

## caculate the loss
loss = F.binary_cross_entropy(a, y)
print(loss)

tensor(0.0852)


##### Method 01: `requires_grad = True`

In [ ]:
from torch.autograd import grad

y = torch.tensor([1.0]) # output
x1 = torch.tensor([1.1]) # intput
w1 = torch.tensor([2.2], requires_grad = True) # weight
b = torch.tensor([0.0], requires_grad= True) # bias

z = x1 * w1 + b # net input
a = torch.sigmoid(z) # activation & output

## caculate the loss
loss = F.binary_cross_entropy(a, y)
grad_L_w1 = grad(loss, w1, retain_graph = True) # indefault it delete the graph to free up space so we set retain_graph = True
grad_L_b = grad(loss, b, retain_graph = True)

In [7]:
print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


##### Method 02: use `.backward`

In [8]:
loss.backward()
print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])
