In [1]:
!nvidia-smi ## need cuda to run

/bin/bash: nvidia-smi: command not found


In [7]:
import torch

In [8]:
torch.rand(3,4)

tensor([[0.4655, 0.2358, 0.5701, 0.2957],
        [0.5476, 0.7468, 0.4441, 0.5812],
        [0.0589, 0.9649, 0.8294, 0.9231]])

In [11]:
torch.rand(3,4)

tensor([[0.1424, 0.6493, 0.2216, 0.1773],
        [0.8556, 0.3602, 0.0097, 0.0124],
        [0.3113, 0.4093, 0.4285, 0.5379]])

In [ ]:
torch.manual_seed(10) ## kind of random state it fixes the rand state
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [13]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])