### Question:
Create a class to handle basic data preprocessing tasks such as normalization, handling missing values, and summary statistics.

In [1]:
import numpy as np

In [2]:
class DataProcessor:
    def __init__(self, data):
        """
        Initialize the DataProcessor with a dataset.
        :param data: A 2D list or NumPy array of numerical data
        """
        self.data = np.array(data)
    
    def normalize(self):
        """
        Normalize the dataset column-wise (Min-Max normalization).
        """
        min_vals = self.data.min(axis=0)
        max_vals = self.data.max(axis=0)
        self.data = (self.data - min_vals) / (max_vals - min_vals)
        return self.data
    
    def fill_missing(self, strategy="mean"):
        """
        Fill missing values in the dataset.
        :param strategy: The strategy to fill missing values, default is 'mean'. Options: 'mean', 'median'.
        """
        for col in range(self.data.shape[1]):
            col_values = self.data[:, col]
            if np.isnan(col_values).any():
                if strategy == "mean":
                    fill_value = np.nanmean(col_values)
                elif strategy == "median":
                    fill_value = np.nanmedian(col_values)
                else:
                    raise ValueError("Unsupported strategy! Use 'mean' or 'median'.")
                col_values[np.isnan(col_values)] = fill_value
                self.data[:, col] = col_values
        return self.data
    
    def summary_statistics(self):
        """
        Compute summary statistics (mean, median, std) for each column.
        :return: A dictionary with summary statistics.
        """
        stats = {
            "mean": np.nanmean(self.data, axis=0),
            "median": np.nanmedian(self.data, axis=0),
            "std": np.nanstd(self.data, axis=0)
        }
        return stats

In [3]:
sample_data = [
    [1.0, 2.0, np.nan],
    [4.0, np.nan, 6.0],
    [7.0, 8.0, 9.0]
]

In [4]:
processor = DataProcessor(sample_data)
print("Original Data:")
print(processor.data)

Original Data:
[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


In [5]:
# Fill missing values
processor.fill_missing(strategy="mean")
print("\nAfter Filling Missing Values:")
print(processor.data)


After Filling Missing Values:
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [6]:
# Normalize the data
normalized_data = processor.normalize()
print("\nNormalized Data:")
print(normalized_data)


Normalized Data:
[[0.  0.  0.5]
 [0.5 0.5 0. ]
 [1.  1.  1. ]]


In [7]:
# Get summary statistics
stats = processor.summary_statistics()
print("\nSummary Statistics:")
print(stats)


Summary Statistics:
{'mean': array([0.5, 0.5, 0.5]), 'median': array([0.5, 0.5, 0.5]), 'std': array([0.40824829, 0.40824829, 0.40824829])}
